[[redirects]]
  from = "/<https://norbertskwierczynski-portfolio.netlify.app/>"
  to = "<https://norbert-knows.co.uk/>"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"